In [3]:
import pandas as pd

series1 = pd.Series([4, 65, 436, 3, 9])
series2 = pd.Series([7, 0, 3, 897, 9])

comparison = series1 == series2
print(comparison)

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [4]:
import pandas as pd

series1 = pd.Series([2, 4, 6, 8, 14])
series2 = pd.Series([1, 3, 5, 7, 9])

addition = series1 + series2
subtraction = series1 - series2
multiplication = series1 * series2
division = series1 / series2

print("Addition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)

Addition:
0     3
1     7
2    11
3    15
4    23
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    5
dtype: int64

Multiplication:
0      2
1     12
2     30
3     56
4    126
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

In [5]:
import pandas as pd

dictionary1 = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}

series = pd.Series(dictionary1)
print(series)

Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

series = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])

array = np.array(series)
print(array)

In [2]:
import pandas as pd
data = pd.read_csv("AfricaCupofNationsMatches.csv")

most_frequent_value = data['HomeTeamGoals'].mode()[0]

data['HomeTeamGoals'] = data['HomeTeamGoals'].apply(lambda x: most_frequent_value if x == most_frequent_value else 'Other')
print(data['HomeTeamGoals'])

0        1.0
1      Other
2      Other
3      Other
4        1.0
       ...
617    Other
618      1.0
619    Other
620    Other
621    Other
Name: HomeTeamGoals, Length: 622, dtype: object

In [3]:
import pandas as pd

data = pd.read_csv('AfricaCupofNationsMatches.csv')

In [6]:
first_seven_rows = data.head(7)
data

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [7]:
selected_columns = data[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]
data

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [ ]:
egypt_rows = data[data['HomeTeam'] == 'Egypt']
data

In [ ]:
num_rows, num_columns = data.shape

In [ ]:
missing_attendance_rows = data[data['Attendance'].isnull()]

In [ ]:
selected_rows = data[(data['HomeTeamGoals'] >= 3) & (data['HomeTeamGoals'] <= 6)]

In [ ]:
data.at[2, 'AwayTeamGoals'] = 10

In [ ]:
sorted_data = data.sort_values(by=['HomeTeam', 'HomeTeamScores'], ascending=[True, False])

In [ ]:
column_headers = list(data.columns)

In [ ]:
data['Countries_left_out'] = ["Uganda", "Rwanda", "Kenya","Zimbabwe"]

In [ ]:
new_rows = pd.DataFrame([[value1, value2, value3, ...], [value4, value5, value6, ...]], columns=data.columns)
data = data.append(new_rows, ignore_index=True)

In [ ]:
data.loc[data['AwayTeam'] == 'Uganda', 'AwayTeam'] = 'China'

In [ ]:
data.reset_index(drop=True, inplace=True)

In [ ]:
if 'Stadium' in data.columns:
    print("The 'Stadium' column is present.")
else:
    print("The 'Stadium' column is not present.")

In [ ]:
data['AwayTeamGoals'] = data['AwayTeamGoals'].astype(float)

In [ ]:
data = data[:-10]

In [ ]:
for index, row in data.iterrows():
    # Access row data using row[column_name]
    # Example: print(row['HomeTeam'], row['AwayTeam'])
    pass  # Replace 'pass' with your code logic